apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: morty-podtato
  namespace: mcp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: morty
  project: default
  source:
    path: 05-workers-bootstrap
    repoURL: https://github.com/AlexandreBrg/cncf-demo-crossplane
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true