apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: mcp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 3.8.4
    helm:
      releaseName: falco
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true