apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
spec:
  projectID: cncf-mtp-demo-argo-crossplane
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: gcp-account-creds
      key: creds

